import "./globals.css";
import { Noto_Sans } from "next/font/google";
import Image from "next/image";
import logo from "../public/book-stack.png";
import Link from "next/link";

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <div className="bg-gray p-2 font-semibold text-center">
          <h1>
            “A reader lives a thousand lives before he dies . . . The man who
            never reads lives only one.” - George R.R. Martin
          </h1>
        </div>

        <div className="bg-white flex flex-row p-3">
          <div className="flex flex-row items-center ml-3">
            <Link href="/">
              <div className="w-10 mr-2">
                <Image src={logo} alt="Logo" />
              </div>
            </Link>
            <div className="font-bold text-4xl">
              <p>ReadSathi</p>
            </div>
          </div>


        </div>

        {children}
      </body>
    </html>
  );
}
